set(PROJECT_TYPE "APP")
set(PROJECT_NAME "PIPP_PCMM")

set(COMPILER_TYPE "HIGHTEC")
set(COMPILER_VER "V4.9.4.1")
set(COMPILER_PATH "C:/HighTec/toolchains/tricore/v4.9.4.1")
set(ARCHITECTURE "AURIX")
set(MICROCONTROLLER "TC3XX")
# set(ROM_SIZE 2000000)
# set(BL_SIZE 128000)
# set(RAM_SIZE 128000)
# set(RAM_START_ADDRESS 0xfebd0000)
set(LNKFILENAME Lcf_Gnuc_Tricore_Tc.lsl)
set(EXECLUDE_DIRS   CSAR_MCAL_TC377/02-SRC/MCU/MCAL/Icu_17_TimerIp
                    CSAR_MCAL_TC377/02-SRC/MCU/MCAL/Gpt
)

set(EXECLUDE_FILES  Ifx_Cfg_SswBmhd.c)

set(CUSTOM_C_FLAGS  -DAUTOSAR_USED -DAPP_SW=NO_DEMO -DNO_DEMO=4 -DDEMO_APP=1 -DTEST_APP=2 -DDEV_APP=3)
set(CUSTOM_ASM_FLAGS )
set(CUSTOM_LINK_FLAGS )
