message("IAR VWS RL78 Specific includes file=============================")

## exclude any DSR folders from External projects
set(EXCLUDE_DSR_EXTERNALS "${PROJECT_DIR}/${EXTDIR}/.*/DSR/.*")


if(NOT DEFINED ${PROJECT_REUSE})
    file(GLOB VWS_INCLUDE_1 "${PROJECT_DIR}/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/" "${PROJECT_DIR}/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/")
    file(GLOB VWS_INCLUDE_2 "${PROJECT_DIR}/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/" 
    "${PROJECT_DIR}/${EXTDIR}/SWC_FSL_T01E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/SWC_FDL_T02E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/SWC_EEL_T02E_RL78*/src/"

    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_FSL_T01E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_FDL_T02E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_EEL_T02E_RL78*/src/"
    "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/")
endif()
if(DEFINED ${PROJECT_REUSE})
    file(GLOB VWS_INCLUDE_1 "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/")
    file(GLOB VWS_INCLUDE_2 "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_FSL_T01E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_FDL_T02E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/SWC_EEL_T02E_RL78*/src/"

    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_LIN_DRIVER_RL78*/BSW/*/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_FSL_T01E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_FDL_T02E_RL78*/src/" 
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_EEL_T02E_RL78*/src/"
    "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/SWC_HWMDU_RL78*/src/RL78_2_core/")
endif()

file(GLOB_RECURSE VWS_SOURCE_FILES "${PROJECT_DIR}/${EXTDIR}/${PROJECT_REUSE}/${EXTDIR}/CSWC_*/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/*.C" "${PROJECT_DIR}/${EXTDIR}/CSWC_BLD_RL78*/03-SRC/05-SHARED/*.C" "${PROJECT_DIR}/${EXTDIR}/CSWC_*/${EXTDIR}/CSWC_BLD_RL78/03-SRC/05-SHARED/*.C"
)
list(APPEND VWS_INCLUDES ${VWS_INCLUDE_1})
list(APPEND VWS_INCLUDES ${VWS_INCLUDE_2})

