if(NOT COMPILER_PATH)
    set(COMPILER_PATH "C:/ghs/comp_201355")
endif()

# Without that flag CMake is not able to pass test compilation check
set(CMAKE_TRY_COMPILE_TARGET_TYPE  "STATIC_LIBRARY")
string(TOLOWER ${ARCHITECTURE} LC_ARCH)
string(TOUPPER ${ARCHITECTURE} UC_ARCH)
string(TOUPPER ${MICROCONTROLLER} UC_MCU)
string(TOLOWER ${COMPILER_TYPE} UC_COMP)
set(DEFAULT_C_FLAGS    )
SET(DEFAULT_ASM_FLAGS  )
set(DEFAULT_LINK_FLAGS )
set(LINKER_FILE_CFG_PAR "")

set(DEFAULT_EXECUTABLE_SUFFIX "out")
set(DEFAULT_HEX_SUFFUX        "hex")

## append compiler include directories
set(COMPILER_INCLUDES ${COMPILER_PATH}/src/libsys ${COMPILER_PATH}/ansi)

set(SOURCE_FILE_EXTENSIONS         c asm 850 s)
set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm 850 s)
set(INCLUDE_FILES_EXTENSIONS       h)

set(CMAKE_C_COMPILER                ${COMPILER_PATH}/ccrh850.exe)
set(GSREC                           ${COMPILER_PATH}/gsrec.exe)

set(POST_BUILD_COMMAND  ${GSREC}  -o ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_HEX_SUFFUX} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_EXECUTABLE_SUFFIX})

set(CMAKE_C_COMPILER_WORKS TRUE)

set(GENERATE_VCSHELL vcshell --inputcmds=build_db.txt putcommand)
