if(NOT COMPILER_PATH)
    set(COMPILER_PATH "C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.3/arm")
endif()

set(DEFAULT_C_FLAGS --silent)
SET(DEFAULT_ASM_FLAGS )
set(DEFAULT_LINK_FLAGS --map ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.map )
set(LINKER_FILE_CFG_PAR --config)

set(DEFAULT_EXECUTABLE_SUFFIX "out")
set(DEFAULT_HEX_SUFFUX        "hex")
set(DEFAULT_EXECUTABLE_SUFFIX_elf "elf")


set(SOURCE_FILE_EXTENSIONS         c asm s)
set(INCLUDE_FILES_EXTENSIONS       h)

set(CMAKE_C_COMPILER                ${COMPILER_PATH}/bin/iccarm.exe)
set(CMAKE_ASM_COMPILER              ${COMPILER_PATH}/bin/iasmarm.exe)
set(ELF_TOOL                        ${COMPILER_PATH}/bin/ielftool.exe)

set(POST_BUILD_COMMAND ${ELF_TOOL} --strip --ihex --verbose ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_EXECUTABLE_SUFFIX} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_HEX_SUFFUX})
set(POST_BUILD_COMMAND_GEN_OUT_EXE ${ELF_TOOL} --strip --verbose ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_EXECUTABLE_SUFFIX} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.${DEFAULT_EXECUTABLE_SUFFIX_elf})

set(GENERATE_VCSHELL vcshell --inputcmds=build_db.txt putcommand)
